// Import components 
import { CMSNavbar } from "@/components/cms-navbar/CMSNavbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CMSNavbar/>
        {children}
      </body>
    </html>
  )
}
