import { Inter, Quattrocento } from "next/font/google"
import "./style/style.scss";

const inter = Inter({
  subsets: ['latin'],
  variable: '$font-inter',
  display: 'swap',
})

const quattrocento = Quattrocento({
  subsets: ['latin'],
  variable: '$font-quattrocento',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${quattrocento.variable}`}>
      <body>
        <div className="wrapper"> 
          <div className="container">
            {children}      
          </div>
        </div>
      </body>
    </html>
  );
}
