import { inter } from './fonts'
import "./style/style.scss";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapper"> 
          <div className="container">
            {children}      
          </div>
        </div>
      </body>
    </html>
  );
}
